# Si 8 atoms
# DFT set up


Mixing_Variable:       potential
Mixing_Type:           broyden
Mixing_MaxDim:         8
Mixing_StepLength:     0.7
#Use_Atom_Density:      1



#Mixing_Variable:       potential
#Mixing_Type:           anderson
#Mixing_Type:           kerker+anderson
#Mixing_StepLength:     0.7
#Mixing_MaxDim:         20
Temperature:           0

Eig_MaxIter: 	       3
Eig_Tolerance:         1e-12
Eig_Min_Tolerance:     1e-9
SCF_Outer_Tolerance:   1e-8
SCF_Outer_MaxIter:     1

PW_Solver:             LOBPCG

PeriodTable:           HGH.bin
Pseudo_Type:           HGH
XC_Type:               XC_LDA_XC_TETER93

Ecut_Wavefunction:     10
#Output_Density:        1

#setup GW
#
GW:                      1
Extra_States:            16
Nv_oper:                 16
Nc_oper:                 16
Nv_ener:           16
Nc_ener:           16
Frequency_Dependence:   COHSEX
Coulomb_screen:         Semiconductor
Coulomb_trunction:      spherical_trunction
spherical_trunction_radius: 5.0
Isisdf: 0
Isdf_method: Kmeans #qrcp #
Iscauchy: 0
Vcrank_ratio:    12
Vsrank_ratio:    12
Ssrank_ratio:    12
Maxiterkmeans_GW_ISDF:    1000
Tolerancekmeans_GW_ISDF:  1e-5
Isrestart: 0
#LRTDDFT set up

#LRTDDFT:               1
#Extra_States:          10
#NvBand:                4
#NcBand:                10
#
#LRTDDFT_ISDF:          0
#NumMuFac_LRTDDFT_ISDF: 4.0
#NumGaussianRandomFac_LRTDDFT_ISDF: 4.0
#Tolerance_LRTDDFT:     1e-8
#
#IPType_LRTDDFT_ISDF:  Kmeans
#MaxIterKmeans_LRTDDFT_ISDF: 50
#ToleranceKmeans_LRTDDFT_ISDF: 1e-5 
#
#EigenSolver_LRTDDFT:   ScaLAPACK # LAPACK # ScaLAPACK # LOBPCG
#NkBand:                10
#EigMaxIter_LRTDDFT:    100
##NumProcEigenSolver_LRTDDFT: 128
#
#Output_Excitation_Energy: 1
#Output_Excitation_Wfn   : 0
Super_Cell: [ 10.3340, 10.3340, 10.3340]

Atom_Types_Num:        1
Atom_Num: [8]
Atom_Type:            [14]

Atom_Red:
- [0.250000, 0.750000, 0.250000]
- [0.000000, 0.000000, 0.500000]
- [0.250000, 0.250000, 0.750000]
- [0.000000, 0.500000, 0.000000]
- [0.750000, 0.750000, 0.750000]
- [0.500000, 0.000000, 0.000000]
- [0.750000, 0.250000, 0.250000]
- [0.500000, 0.500000, 0.500000]
